version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
    # set the env variable to store url for backend,
      - NEXT_PUBLIC_TRANSLATOR_API_URL=http://172.17.0.1:8000
    depends_on:
      - backend
